### ISSUE TITLE
現在似乎都出現"查無符合的商品."

### ISSUE THREAD

**Issue by chkuo2** [wsmwason/ruten-to-rss#1]
https://jackteacher.cc/ruten-to-rss/example.php?result_url=http://search.ruten.com.tw/search/s000.php?enc=u&searchfrom=goodsheadbar&k=%E3%80%90ARZ%E3%80%91
請問還可以正常使用嗎？

**Comment by wsmwason** [comment]
如果沒有特別改過 example.php 的話，
result_url 應該會是 base64_decode 過後的 URL 才對（可用 converter.php 的 from 產生它）
所以你這個搜尋結果應該會是：

> example.php?result_url=aHR0cDovL3NlYXJjaC5ydXRlbi5jb20udHcvc2VhcmNoL3MwMDAucGhwP2VuYz11JnNlYXJjaGZyb209Z29vZHNoZWFkYmFyJms9JUUzJTgwJTkwQVJaJUUzJTgwJTkx

目前測試是 OK 的，如果不行的話，可能要看看是不是被 ruten 用 IP 黑單了。
